Models/InvoiceLineItem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurrisProject3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineItem
    {
        public int InvoiceID { get; set; }
        public string ProductCode { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public decimal ItemTotal { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}

Controllers/InvoiceLineItemController.cs
using System.Data.Entity.Migrations;
using BurrisProject3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BurrisProject3.Controllers
{
    public class InvoiceLineItemController : Controller
    {

        public ActionResult InvoiceLineItems(string id, int sortBy = 0) {
            //creation of the entity and list of customers for future display
            BookEntities context = new BookEntities();
            List<InvoiceLineItem> iLineItem = context.InvoiceLineItems.ToList();

            switch (sortBy) {
                //default sorting will be by customer id
                case 0:
                default: {
                    iLineItem = context.InvoiceLineItems.OrderBy(c => c.InvoiceID).ToList();
                    break;
                }
                case 1: {
                    iLineItem = context.InvoiceLineItems.OrderBy(c => c.ProductCode).ToList();
                    break;
                }
                case 2: {
                    iLineItem = context.InvoiceLineItems.OrderBy(c => c.UnitPrice).ToList();
                    break;
                }
                case 3: {
                    iLineItem = context.InvoiceLineItems.OrderBy(c => c.Quantity).ToList();
                    break;
                }
                case 4: {
                    iLineItem = context.InvoiceLineItems.OrderBy(c => c.ItemTotal).ToList();
                    break;
                }
            } //end switch

            if (!string.IsNullOrWhiteSpace(id)) {
                id = id.Trim().ToLower();
                iLineItem = iLineItem.Where(i =>
                    i.ProductCode.ToLower().Contains(id) 
                ).ToList();
            }

            return View(iLineItem);
        }

        // GET: InvoiceLineItem
        [HttpGet]
        public ActionResult Upsert(int invoiceId, string productCode)
        {
            BookEntities context = new BookEntities();
            InvoiceLineItem lineItem = context.InvoiceLineItems.Where(i => i.InvoiceID == invoiceId && i.ProductCode == productCode).FirstOrDefault();

            if (lineItem == null) {
                lineItem = new InvoiceLineItem();
                lineItem.InvoiceID = invoiceId;
            }


            return View(lineItem);
        }

        [HttpPost]
        public ActionResult Upsert(InvoiceLineItem lineItem) {
            BookEntities context = new BookEntities();
            try {
                lineItem.ItemTotal = lineItem.Quantity * lineItem.UnitPrice;

                context.InvoiceLineItems.AddOrUpdate(lineItem);
                context.SaveChanges();
            }
            catch (Exception) {

                throw;
            }

            return Redirect("/Invoice/Upsert/" + lineItem.InvoiceID.ToString());
        }
    }
}

Views/InvoiceLineItem/InvoiceLineItems.cshtml
@model List<BurrisProject3.Models.InvoiceLineItem>

@{
    ViewBag.Title = "Invoice Line Items";
}

<h2>Invoice Line Items</h2>

<a href="/InvoiceLineItem/Upsert">Add New Line Item</a>
<div class="row">
    <div class="col-md-6">
        <input id="txtSearch" type="text" class="form-control" placeholder="Search..." />
    </div>
    <div class="col-md-6">
        <input type="button" class="btn btn-info" value="Search" onclick="Sortable.Search();" />
    </div>
</div>
<table class="sortable table table-bordered table-hover">
    <thead>
        <tr>
            <th onclick="Sortable.Sort(0)" class="tableHeader">Invoice ID</th>
            <th onclick="Sortable.Sort(1)" class="tableHeader">Product Code</th>
            <th onclick="Sortable.Sort(2)" class="tableHeader">Unit Price</th>
            <th onclick="Sortable.Sort(3)" class="tableHeader">Quantity</th>
            <th onclick="Sortable.Sort(4)" class="tableHeader">ItemTotal</th>
            <th class="tableHeader">Actions</th>
        </tr>
    </thead>
    <tbody>
        @* Loop through the customers list *@
        @foreach (var items in Model) {
            <tr>
                <td>@items.InvoiceID</td>
                <td>@items.ProductCode</td>
                <td>@items.UnitPrice</td>
                <td>@items.Quantity</td>
                <td>@items.ItemTotal</td>
                <td>
                    <a href="/InvoiceLineItem/Upsert/@items.InvoiceID">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    Sortable.baseUrl = '/InvoiceLineItem/InvoiceLineItems/';
</script>

Views/InvoiceLineItem/Upsert.cshtml
@model BurrisProject3.Models.InvoiceLineItem
@{
    ViewBag.Title = "Upsert";
}

<h2>Upsert</h2>

@using (Html.BeginForm("Upsert", "InvoiceLineItem", FormMethod.Post)) {
<span>Invoice ID</span> @Html.HiddenFor(i => i.InvoiceID);
<span>Product Code</span> @Html.TextBoxFor(i => i.ProductCode);
<span>Unit Price</span> @Html.TextBoxFor(i => i.UnitPrice);
<span>Quantity</span> @Html.TextBoxFor(i => i.Quantity);

    <button type="submit">Submit</button>
}